name: build and ship APK

on:
  push:
    branches:
      - main
    paths:
      - phone/KeyDisplayUnit/
  workflow_dispatch:

jobs:
  apk:
    name: Generate APK
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Setup JDK
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build APK
      run: cd phone/KeyDisplayUnit && bash ./gradlew assembleDebug --stacktrace
    - name: Upload APK
      uses: actions/upload-artifact@v1
      with:
        name: apk
        path: phone/KeyDisplayUnit/app/build/outputs/apk/debug/app-debug.apk 
  release:
    name: Release APK
    needs: apk
    runs-on: ubuntu-latest
    steps:
      - name: set env
        run: echo "NOW=$(date +'%Y.%m.%d')" >> $GITHUB_ENV

      - name: download APK from build
        uses: actions/download-artifact@v1
        with:
          name: apk 

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        with:
          tag_name: ${{ env.NOW }}
          release_name: Release ${{ env.NOW }}

      - name: Upload Release APK
        id: upload_release_asset
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: apk/app-debug.apk
          asset_name: sw-kdu.apk
          asset_content_type: application/zip
